
spring.application.name=wordexcel

server.port=8081

logging.level.root=ERROR
logging.level.com.example=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration